### ISSUE TITLE
Travis CI builds are broken

### ISSUE THREAD

**Issue by jbasney** [scitokens/scitokens#125]
Since June 15th, 2021, the building on travis-ci.org is ceased. See: https://blog.travis-ci.com/2021-05-07-orgshutdown

Need to decide if we want to migrate to travis-ci.com.

For now, I've removed continuous-integration/travis-ci from the list of status checks required to pass before merging.

**Comment by brianhlin** [comment]
Given how they handled the [latest security issue](https://arstechnica.com/information-technology/2021/09/travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects/), I'd just move everything over to GHA if it hasn't been already.

**Comment by duncanmmacleod** [comment]
GHA has been supported since 486efff121c1f92ecc45effad96210c1550ce431, I think this can be closed; ping @djw8605.
