### ISSUE TITLE
Cache JWKS trust roots

### ISSUE THREAD

**Issue by bbockelm** [scitokens/scitokens#13]
We should cache trust roots per-issuer from JWKS URI.  The cache should provide a mapping from issuer URI to a map of signing key IDs to public keys.

A few aspects of the design:
- Instead of wedging this into a file hierarchy, I'd like to explore using a simple database (SQLite?).
- This will need to be done per-Unix-user.  Look at the `$XDG_CACHE_DIR` definition for inspiration on where to put the database.  The location of the DB should be overridden by an environment variable.

**Comment by bbockelm** [comment]
@djw8605 - I know there has been a lot of activity along these lines in the last few days.  What's the current status?

**Comment by djw8605** [comment]
The keycache was merged in eb33c0c54b221cf17f743b505fdac36caab5bba2, d6c19998b9997bd9a0c417e753fb23a2f74cb236.

It doesn't have dedicated unittests yet, but normal test_with_http does go through the test.  I'm writing unittests now.

**Comment by bbockelm** [comment]
Ok, let's keep this ticket open until the unit tests are done.  Thanks for the updates!

**Comment by bbockelm** [comment]
What are the status of the unit tests here?
