### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by duncanmmacleod** [scitokens/scitokens#143]
It would be nice to get a new release (1.6.3? 1.7.0?) to include #137, #138, and #141, at least.

**Comment by duncanmmacleod** [comment]
Ping @djw8605.

**Comment by djw8605** [comment]
Hi, yes I can cut this release.

**Comment by djw8605** [comment]
Released: 1.7.0: https://pypi.org/project/scitokens/

**Comment by duncanmmacleod** [comment]
I have opened an OSG Jira ticket to request RPMs for this release: https://opensciencegrid.atlassian.net/browse/SOFTWARE-5067.

**Comment by djw8605** [comment]
Thanks!
