### ISSUE TITLE
Toy CLI for creating new signing keys

### ISSUE THREAD

**Issue by bbockelm** [scitokens/scitokens#34]
We have recently added a CLI tool for creating signing tokens -- and there's a pending PR for creating an appropriately-formatted public key (#31).

We should create a separate tool for generating new private keys -- or add this capability to one of the existing tools.

**Comment by djw8605** [comment]
This is done in #31.  Will close this when #31 has been merged.

**Comment by djw8605** [comment]
Done in #31
